'use strict';

var _         = require('lodash');
var Q         = require('q');
var request   = require('request');
var xmlParser = require('xml2json');
var logger    = require('yocto-logger');
var moment    = require('moment');

/**
 * Default module for giftCard request
 */
function GiftCard (l) {
  /**
   * Default logger instance
   */
  this.logger = l;

  /**
   * Default config instance
   */
  this.config = {};
}

/**
 * Default use method to setup config
 *
 * @param {Object} config default config
 * @return {Boolean} true when config is set
 */
GiftCard.prototype.use = function (config) {
  // set config
  this.config = config;
  // default statement
  return true;
};

/**
 * Default method to getBalance from a cardNumber & password
 *
 * @param {String} cardNumber default card number
 * @param {String} password default password to use
 * @return {Object} default promise to catch
 */
GiftCard.prototype.getBalance = function (cardNumber, password) {

  // error lists
  var errors = [
    { code : '00' },
    { code : '02', message : 'Carte ou compte bloqué' },
    { code : '03', message : 'VU nombre n\'est pas connu' },
    { code : '30', message : 'Requête invalide' },
    { code : '33', message : 'Votre carte à expirée' },
    { code : '43', message : 'Votre carte est inactive' },
    { code : '55', message : 'Votre code pin est invalide' },
    { code : '56', message : 'Carte Inconnue' },
    { code : '91', message : 'Erreur interne au système' },
    { code : '-1', message : 'Impossible de connaitre votre solde' }
  ];

  // Create defer process
  var deferred = Q.defer();

  // get current Date
  var currentDate = moment();

  // default sequence to use on request
  var sequence = moment().unix();

  // build form request
  var formRequest = {
    'MessageType'   : 200,
    'CardNumber'    : cardNumber,
    'RequestType'   : '00',
    'Amount'        : 0,
    'TraceNumber'   : sequence,
    'Time'          : currentDate.format('hhmmss'), // Need to be generated by app
    'Date'          : currentDate.format('MMDD'), // Need to be generated by app
    'expiryDate'    : 4912,
    'entryMode'     : '03',
    'Pin'           : password,
    'PinLength'     : _.size(password),
    'Condition'     : '00',
    'Terminal-ID'   : 99999999,
    'Branch-ID'     : 777777,
    'Currency'      : 978,
    'Sequence'      : sequence
  };

  // process request
  request.post({
    uri       : [ this.config.uri, 'DoTransactionProcessing' ].join('/'),
    form      : formRequest
  }, function (error, response, body) {
    //console.log('body', body);
    // has no error ?
    if (!error && response.statusCode === 200) {
      // parse response
      var  result = xmlParser.toJson(body, { object : true, trim : true });

      // has valid format ?
      if (_.has(result, 'AutSys.Reply')) {
        // get json reply only
        var reply = _.get(result, 'AutSys.Reply');
        // has a reponse code
        if (_.has(reply, 'ResponseCode')) {
          // response code
          var code    = _.get(reply, 'ResponseCode');
          // response message
          var message = _.first(_.values(_.pickBy(errors, function (error) {
            // default statement
            return error.code === code;
          })));

          // has error ?
          if (code !== '00') {

            // reject error
            this.logger.error([ '[ Ingenico.giftCard.GetBalance ] -',
              'Invalid response code retreive from GetBalance call. Code :', code,
              '- Message :', _.get(message, 'message') || _.get(reply, 'Message') ].join(' '));
            // reject with an object
            deferred.reject({
              code      : _.isString(code) || _.isNumber(code) ? code : 'Unkown Code',
              message   : _.get(message, 'message') || _.get(reply, 'Message')
            });
          } else {
            var regex = /(.*)(:)(\s+)(\d+.+)(\s+)(.*)/gm;
            // return with new data
            deferred.resolve(((_.get(reply, 'Message') || '0').replace(regex, `$4`)));
          }
        } else {
          // reject with message
          deferred.reject([ 'Cannot retrive reponse code from response :', body ].join(' '));
        }
      } else {
        // reject error
        deferred.reject([ 'Invalid format retreive from GetBalance call', result ].join(' '));
      }
    } else {
      // reject
      deferred.reject(error);
    }
  }.bind(this));

  // default statement
  return deferred.promise;
};

/**
 * Export GiftCard from Ingenico
 */
module.exports = function (l) {
  // is a valid logger ?
  if (_.isUndefined(l) || _.isNull(l)) {
    // log warning message
    logger.warning('[ Ingenico.GiftCard.constructor ] - Invalid logger given. Use internal logger');
    // assign new logger instance
    l = logger;
  }
  // default statement
  return new (GiftCard)(l);
};
